openapi: 3.1.0
info:
  version: 1.0.0
  title: sugar_control
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Supporting documentation for working with the blood sugar monitoring backend.
tags:
  - name: User
    description: User registration
  # - name: Product
  #   description: List of medicines
  # - name: Order
  #   description: List of items in the cart
servers:
  - url: http://localhost:3000
  - url: https://blood-sugar-control-backend.onrender.com
paths:
  /api/user/register:
    post:
      $ref: ../docs/swagger/paths/auth/postRegister.yaml
# /api/user/login:
#   post:
#     $ref: ../docs/swagger/paths/auth/postLogin.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
