openapi: 3.1.0
info:
  version: 1.0.0
  title: sugar_control
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Supporting documentation for working with the blood sugar monitoring backend.
tags:
  - name: User
    description: User registration
  - name: Measurements
    description: Measuring blood sugar levels
servers:
  - url: http://localhost:3000
  - url: https://blood-sugar-control-backend.onrender.com
paths:
  /api/user/register:
    post:
      $ref: ../docs/swagger/paths/auth/postRegister.yaml
  /api/user/login:
    post:
      $ref: ../docs/swagger/paths/auth/postLogin.yaml
  /api/user/logout:
    post:
      $ref: ../docs/swagger/paths/auth/postLogout.yaml
  /api/user/userInformation:
    get:
      $ref: ../docs/swagger/paths/auth/getUserinformation.yaml
  /api/user/updating:
    get:
      $ref: ../docs/swagger/paths/auth/putUpdating.yaml
  /api/measurements/add:
    post:
      $ref: ../docs/swagger/paths/measurements/postAddMeasurements.yaml
  /api/measurements/all-dimensions:
    get:
      $ref: ../docs/swagger/paths/measurements/getAllDimensions.yaml
  /api/measurements/in-one-day:
    get:
      $ref: ../docs/swagger/paths/measurements/getInOneDay.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
